import React from "react";
import Head from "next/head";
import AuthComponent from "../../components/AuthComponent";

const index = () => {
  return (
    <div>
      <Head>
        <title>Login | Signup</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <span className="screen-darken"></span>
      <AuthComponent />
    </div>
  );
};

export default index;
